function(openapi_to_proto PROTOS)
    set(_generated_srcs)
    foreach(file ${ARGN})
        string(REGEX REPLACE ".yaml" ".proto" proto ${file})
        list(APPEND _generated_srcs ${proto})

        add_custom_command(
            OUTPUT ${proto}
            COMMAND echo ${proto}
            COMMAND openapi2proto -add-autogenerated-comment -spec ${file} -out ${proto}
            COMMENT "Running openapi2proto generator"
            DEPENDS ${proto}
            VERBATIM
        )
    endforeach()
    set_source_files_properties(${_generated_srcs} PROPERTIES GENERATED TRUE)
    set(PROTOS ${_generated_srcs} PARENT_SCOPE)
endfunction()

# Find the openapi2proto Executable
find_program(openapi2proto_EXECUTABLE
    NAMES openapi2proto
    DOC "A tool for generating Protobuf v3 schemas and gRPC service definitions from OpenAPI specifications"
    PATHS $ENV{HOME}/go/bin
)
mark_as_advanced(openapi2proto_EXECUTABLE)